# Generated by Django 3.0.7 on 2020-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimeurl',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
