# Generated by Django 3.0.7 on 2020-06-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingapp', '0002_auto_20200616_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datetimeurl',
        ),
    ]
